server:
  port: 8083
spring:
  application:
    name: literature-core-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
  ai:
    openai:
      api-key:  sk-your-api-key
      base-url: https://xxx
    vectorstore:
      simple:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: your-rabbitmq-password
    listener:
      simple:
        acknowledge-mode: manual
  redis:
    host: 127.0.0.1
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/literature_db?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: your-mysql-password

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
